schema: v1
generation: v32
cache:
  address: 127.0.0.1:6379
context:
  version: 1.0.0
  vendor: grcc
  directory: .
  basepath: unknown
  address: 127.0.0.1
  modality: photo
  port: 8081
  base_path: unknown
  content_range:
    min: 16
    max: 5000000
  template_range:
    min: 16
    max: 260